### PR TITLE
Correct issues with compatibility of recent ecosystem releases

### LINKED ISSUE #41: Compatibility with `docutils>=0.19`
Hi. With 7faeb4f, we limited runtime dependencies to `docutils<0.19`. When upgrading, the tests croak like this.

```python
______ ERROR collecting tests/test_csv.py ______
tests/test_csv.py:49: in <module>
    directive = CSVFilterDirective(
.venv/lib/python3.11/site-packages/docutils/parsers/rst/__init__.py:331: in __init__
    self.reporter = state_machine.reporter
E   AttributeError: 'NoneType' object has no attribute 'reporter'
```

### LINKED ISSUE #42: Compatibility with `flake8>=5`
Hi. With 500a3914772, we limited testing dependencies to `flake8<5`. When upgrading, the tests croak like this.

```python
>       prelim_opts, remaining_args = app.parse_preliminary_options(args)
E       AttributeError: 'Application' object has no attribute 'parse_preliminary_options'

/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pytest_flake8.py:216: AttributeError
```

-- https://github.com/crate/sphinx_csv_filter/actions/runs/3664718574/jobs/6195314760#step:5:1739

### PR DESCRIPTION
**Pull request by freakboy3742**
This PR makes a number of updates for compatibility with the state of dependencies as currently published.

* Fixes #42 - Drops the `flake8<5` pin, as the underlying compatibility issue with flake8, as the underlying issue (tholo/pytest-flake8#66) has been resolved.
* Fixes #41 - Removes the `docutils` dependency completely. docutils is a dependency of Sphinx; and as of Sphinx 7.4.7 imposes a docutils version range that is incompatible with the previous version pin. This required a minor change to a test configuration, but otherwise appears to run without error.
* Modifies CI to run on Ubuntu 22.04 (as the 20.04 image is nearing deprecation)
* Adds a CI configuration for Python 3.12 and 3.13, removing 3.6 and 3.7 (which are no longer supported releases)
* Removes the Trove classifiers indicating support for unsupported releases, as they can't be tested.
* Adds a minimal tox configuration to make it easier to test different Python releases and dependency versions. 

With these changes, `sphinx-csv-filter` can be used in a Sphinx 7.4.7 install. 

If accepted, it would be extremely helpful if these changes were published in a new release. There hasn't been a release in over 2 years, and it isn't currently possible to install `sphinx-csv-filter` with Sphinx 7.4.7.

## Checklist

 - [x] Link to issue this PR refers to (if applicable): 
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by freakboy3742** [comment]
A polite nudge on this; it's been 2 weeks without any response from the maintainers.

**Comment by freakboy3742** [comment]
Another polite nudge on this; it's now been a month since I submitted this PR. 

@amotl Tagging since you seem to be the most recent activity on the repo; are you able to provide any guidance on the current status of this project?

**Comment by amotl** [comment]
Hi @freakboy3742,

thank you for tagging, this has been missed before. I will try to have a look.

With kind regards,
Andreas.

**Review by amotl — APPROVED** [review]
lgtm. Thank you very much.

**Comment by amotl** [comment]
Merged. Something with CI/GHA is failing, see https://github.com/crate/sphinx_csv_filter/actions/runs/10488592973/job/29051407699. Can you take a look at it?

**Comment by amotl** [comment]
Version 0.4.2 has been released, including your improvements, thanks again. We hope it improves the situation for you.

-- https://pypi.org/project/sphinx-csv-filter/

**Pull request merged**
